---
deployment:
  tasks:
    - /bin/cp -R index.html /home/pari3284/avenue18k.com/
    - /bin/cp -R boutique.html /home/pari3284/avenue18k.com/
    - /bin/cp -R produit.html /home/pari3284/avenue18k.com/
    - /bin/cp -R panier.html /home/pari3284/avenue18k.com/
    - /bin/cp -R contact.html /home/pari3284/avenue18k.com/
    - /bin/mkdir -p /home/pari3284/avenue18k.com/css
    - /bin/cp -R css/. /home/pari3284/avenue18k.com/css/
    - /bin/mkdir -p /home/pari3284/avenue18k.com/js
    - /bin/cp -R js/. /home/pari3284/avenue18k.com/js/
